{
  "entities": [
    "edugain": {
      "displayname": "eduGAIN",
      "type": "ta",
      "url" "https://edugain.oidfed.lab.surf.nl",
      "subordinates": [
        "refeds": {
          "displayname": "REFEDs"
          "type": "tmo"
          "url" "https://refeds.oidfed.lab.surf.nl"
          "trustmarks": [
            {
              "name": "Sirtifi"
              "issuers": [],
            },
          ],
        },
        "erasmus_plus": {
          "displayname": "Erasmus Plus"
          "type": "tmi"
          "url" "https://erasmus_plus.oidfed.lab.surf.nl"
            "trustmarks": [
            {
              "name": "Erasmus+"
            },
          ]
        },
        "surfconext": {
          "displayname": "SURFconext - Netherlands",
          "type": "ta",
          "url" "https://surfconext.oidfed.lab.surf.nl",
          "subordinates": [
            "surf-rp": {
              "displayname": "Test RP in SURFconext",
              "type": "rp",
              "url" "https://surf-rp.oidfed.lab.surf.nl",
            },
            "surf-op": {
              "displayname": "Test OP in SURFconext",
              "type": "op",
              "url" "https://surf-op.oidfed.lab.surf.nl",
            },
          ],
        },
        "swamid": {
          "displayname": "SWAMid - Sweden",
          "type": "ta",
          "url" "https://swamid.oidfed.lab.surf.nl",
          "subordinates": [
            "swamid-rp": {
              "displayname": "Test RP in SWAMid",
              "type": "rp",
              "url" "https://swamid-rp.oidfed.lab.surf.nl",
            },
            "swamid-op": {
              "displayname": "Test OP in SWAMid",
              "type": "op",
              "url" "https://swamid-op.oidfed.lab.surf.nl",
            },
          ]
        },
      ]
    },
  ]  
}