server_port: 8765
entity_id: "https://edugain.$testbed_domain"
signing_key_file: "/data/signing.key"
organization_name: "eduGAIN"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  resolve:
    path: "/resolve"
  trust_mark:
    path: "/trustmark"
  trust_mark_status:
    path: "/trustmark/status"
  trust_mark_list:
    path: "/trustmark/list"
trust_mark_specs:
  - trust_mark_id: "https://edugain.org/member"
    lifetime: 7200
    logo_uri: "https://edugain.org/wp-content/uploads/2018/02/eduGAIN.jpg"
    checker:
      type: trust_path
      config:
        trust_anchors:
          - entity_id: "https://nl.surfconext.$testbed_domain"
          - entity_id: "https://it.idem.$testbed_domain"
          - entity_id: "https://us.incommon.$testbed_domain"
          - entity_id: "https://fi.haka.$testbed_domain"
          - entity_id: "https://se.swamid.$testbed_domain"
trust_mark_issuers:
  https://edugain.org/member:
    - "https://edugain.$testbed_domain"
  https://erasmus-plus.ec.europa.eu:
    - "https://erasmus-plus.$testbed_domain"
  "http://www.csc.fi/haka/member":
    - "https://haka.$testbed_domain"
  "https://puhuri.io":
    - "https://puhuri.$testbed_domain"
  https://incommon.org/federation/member:
    - "https://incommon.$testbed_domain"
trust_mark_owners:
  "https://refeds.org/sirtfi":
    entity_id: "$refeds_tmo_url"
    jwks: $refeds_jwks
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "https://edugain.$testbed_domain"
