server_addr: 8765
entity_id: 
authority_hints: []
trust_anchors: []
signing_key_file: "/data/signing.key"
organization_name: 
key_storage: /data
filter_to_automatic_ops: false
enable_debug_log: false
trust_marks: []
