server_port: 8765
entity_id: "$entity_id"
authority_hints:
  - "$ta"
signing_key_file: "/data/signing.key"
organization_name: "$orgname"
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  trust_mark:
    path: "/trust_mark"
  trust_mark_status:
    path: "/trust_mark/status"
  trust_mark_list:
    path: "/trust_mark/list"
trust_mark_specs:
  - trust_mark_id: "https://refeds.org/sirtfi"
    lifetime: 86400
    ref: "https://refeds.org/wp-content/uploads/2022/08/Sirtfi-v2.pdf"
    delegation_jwt: %REFEDS_DELEGATION_JWT_GARR%
    checker:
      type: none
trust_mark_owners:
  "https://refeds.org/sirtfi":
    entity_id: "$refeds_tmo_url"
    jwks: %REFEDS_JWKS%
trust_marks:
  - trust_mark_id: "https://edugain.org/member"
    trust_mark_issuer: "$edugain_member_tmi_url"
  - trust_mark_id: "https://refeds.org/sirtfi"
    trust_mark_issuer: "$refeds_sirtfi_tmi_url"
