server_port: 8765
entity_id:
authority_hints: []
signing_key_file: "/data/signing.key"
organization_name:
data_location: "/data/data"
human_readable_storage: true
metadata_policy_file: "/data/metadata-policy.json"
endpoints:
  fetch:
    path: "/fetch"
  list:
    path: "/list"
  trust_mark:
    path: "/trust_mark"
  trust_mark_status:
    path: "/trust_mark/status"
  trust_mark_list:
    path: "/trust_mark/list"
trust_mark_specs: {}
trust_mark_owners: {}
trust_marks: []